### PR TITLE
Specification of a local GraphQL JSON schema file.

### PR DESCRIPTION
**Pull request by righettod**
Hi,

I have added the support for the specification of a local GraphQL JSON schema file because i have meet recently the case in with i cannot access the Introspection endpoint but i can retrieve the schema as a JSON file.

I have added a sample schema file in attachement: [schema.zip](https://github.com/doyensec/graph-ql/files/2730420/schema.zip)

Thanks you in advance :smiley:

### CODE REVIEW

**Comment by ikkisoft** [comment]
Hi @righettod - thanks a lot for the PR. We will take a look during the next few days.

**Comment by righettod** [comment]
OK thanks you for the feedback.

**Comment by VoidSec** [comment]
Hi @righettod your PR was merged with some minor fixes (printing out the parser.print_help() when target or localschema is missing). Thanks a lot for your work, much appreciated :)

**Comment by righettod** [comment]
You are welcome, 
Thanks you to you for this very useful script :smiley:

**Pull request merged**
